spring:
  application:
    name: kafkastream

  kafka:
    bootstrap-servers: kafka:9092
    properties:
      spring.json.trusted.packages: "*"

    streams:
      application-id: ttn-uplink-stream
      bootstrap-servers: kafka:9092
      properties:
        processing.guarantee: at_least_once
        auto.offset.reset: earliest
        #default.key.serde: org.apache.kafka.common.serialization.Serdes$ByteArraySerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        spring.json.trusted.packages: "*"

logging:
  level:
    root: INFO
    # Silenzia completamente la valanga di log interni dei client Kafka
    org.apache.kafka: WARN
    org.apache.kafka.clients: WARN
    org.apache.kafka.streams: WARN

    # Abilita i log di DEBUG/INFO solo per il tuo codice
    it.polito.measurestream.kafkastream: DEBUG
